import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { provideIcons, provideNgIconsConfig } from '@ng-icons/core';
import {
  lucideAlertCircle,
  lucideAlertTriangle,
  lucideAlignCenter,
  lucideAlignLeft,
  lucideAlignRight,
  lucideArrowRight,
  lucideCalendar,
  lucideCheck,
  lucideCheckCircle,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideDownload,
  lucideEye,
  lucideEyeOff,
  lucideHome,
  lucideInbox,
  lucideInfo,
  lucideLayoutDashboard,
  lucideList,
  lucideMail,
  lucideMenu,
  lucideMinus,
  lucidePlus,
  lucideSearch,
  lucideSend,
  lucideSettings,
  lucideStar,
  lucideTrash2,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideUser,
  lucideUsers,
  lucideX,
  lucideXCircle,
} from '@ng-icons/lucide';
import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideHttpClient(),
    provideRouter(routes, withComponentInputBinding()),
    provideNgIconsConfig({ size: '1em' }),
    provideIcons({
      lucideAlertCircle,
      lucideAlertTriangle,
      lucideAlignCenter,
      lucideAlignLeft,
      lucideAlignRight,
      lucideArrowRight,
      lucideCalendar,
      lucideCheck,
      lucideCheckCircle,
      lucideChevronDown,
      lucideChevronLeft,
      lucideChevronRight,
      lucideDownload,
      lucideEye,
      lucideEyeOff,
      lucideHome,
      lucideInbox,
      lucideInfo,
      lucideLayoutDashboard,
      lucideList,
      lucideMail,
      lucideMenu,
      lucideMinus,
      lucidePlus,
      lucideSearch,
      lucideSend,
      lucideSettings,
      lucideStar,
      lucideTrash2,
      lucideTrendingDown,
      lucideTrendingUp,
      lucideUser,
      lucideUsers,
      lucideX,
      lucideXCircle,
    }),
  ],
};
